### ISSUE TITLE
Include mlr3spatiotempcv?

### ISSUE THREAD

**Issue by pat-s** [mlr-org/mlr3verse#14]
Any opinions @mllg ?

**Comment by pat-s** [comment]
I would issue a PR if nothing speaks against it.

**Comment by berndbischl** [comment]
pls wait here, see discussion in core channel

**Comment by sebffischer** [comment]
all extension packages are now at least listed in suggests: https://github.com/mlr-org/mlr3verse/commit/3b150d1071e45bb4c1ccecd8469e933e7b7a468a
