### ISSUE TITLE
Move depends to imports?

### ISSUE THREAD

**Issue by mllg** [mlr-org/mlr3verse#2]
In the packges we have listed in Depends, we actually don't have many functions a typical user would call. E.g., for mlr3learners, it would be okay to have the dictionary populated, so this could easily go to imports. For mlr3filters, it would probably be okay to just re-export the dictionary + sugar function...

**Comment by pat-s** [comment]
Wouldn't this just confuse the user? Some packages are auto-loaded (even with a messaage), for some others we selectively only import the dictionaries?

What would be better afterwards?

**Comment by berndbischl** [comment]
i dont think that "imports" works. in 100% of my current scripts i start with 5x library statements... because i need them

**Comment by pat-s** [comment]
@mllg Is your current opinion still that a selective import would be better?

**Comment by mllg** [comment]
Yes, I still believe it would be helpful.
